name: SHMR-Finance CI/CD

on:
  push:
    branches: [ master ]  # Триггер на пуши в master
  pull_request:
    branches: [ master ]  # Триггер на PR в master

jobs:
  build:
    runs-on: ubuntu-latest  # Используем Ubuntu

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.20.0
        with:
          flutter-version: '3.29.2'

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            /opt/hostedtoolcache/flutter
            .pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

      - name: Install dependencies
        run: flutter pub get
      - name: Generate localization files
        run: flutter gen-l10n
      - name: List generated l10n files
        run: ls -lR .dart_tool/flutter_gen/gen_l10n || true

#      - name: Run tests
#        run: flutter test

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Build APK (release)
        run: flutter build apk --release
